/*
Sniperkit-Bot
- Status: analyzed
*/

package fontawesomecss

import (
	"net/http"
)

// This code is generated by createhandlerlib
// github.com/as27/createhandlerlib

// Version of the library
const Version = "4.7.0"

// Handler can be used from http Server
func Handler(w http.ResponseWriter, r *http.Request) {
	w.Header().Add("Content-Type", "text/css")
	w.Write(libBytes)
}
